# generate-feeds.ps1 — TABI
# Generates sitemap.xml, rss.xml, robots.txt

$ErrorActionPreference = 'Stop'
$root    = Split-Path $PSScriptRoot -Parent
$config  = Get-Content "$root\site.config.json" -Raw -Encoding UTF8 | ConvertFrom-Json
$articles = Get-Content "$root\articles.json" -Raw -Encoding UTF8 | ConvertFrom-Json

# See generate-pages.ps1: TABI_SITE_URL overrides the site URL for local preview builds.
$siteUrl  = if ($env:TABI_SITE_URL) { $env:TABI_SITE_URL.TrimEnd('/') } else { $config.siteUrl }
$today    = (Get-Date).ToString('yyyy-MM-dd')

# RFC-822 dates in RSS must use English day and month names. Without an explicit
# culture these follow the machine locale, which produced dates like "水, 17 6 2026".
$invariant = [System.Globalization.CultureInfo]::InvariantCulture

# ===== sitemap.xml =====
$sm = [System.Collections.Generic.List[string]]::new()
$sm.Add('<?xml version="1.0" encoding="UTF-8"?>')
$sm.Add('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')

# Top page
$sm.Add("  <url><loc>$siteUrl/</loc><changefreq>daily</changefreq><priority>1.0</priority></url>")

# All-articles archive
$sm.Add("  <url><loc>$siteUrl/articles.html</loc><changefreq>daily</changefreq><priority>0.9</priority></url>")

# Category pages
foreach ($cat in $config.categories) {
    $sm.Add("  <url><loc>$siteUrl/categories/$($cat.slug).html</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>")
}

# Article pages
foreach ($a in $articles) {
    $lastmod = if ($a.updatedAt) { $a.updatedAt } else { $a.publishedAt }
    $sm.Add("  <url><loc>$siteUrl/articles/$($a.id).html</loc><lastmod>$lastmod</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>")
}

# Tag pages -- generated by generate-pages.ps1 but previously absent from the sitemap.
$tagList = @($config.tags + @($articles | ForEach-Object { $_.tags }) | Where-Object { $_ } | Sort-Object -Unique)
foreach ($tag in $tagList) {
    $sm.Add("  <url><loc>$siteUrl/tags/$tag.html</loc><changefreq>weekly</changefreq><priority>0.5</priority></url>")
}

# Static pages
foreach ($p in @('about.html','contact.html','newsletter.html','affiliate.html','privacy.html','terms.html')) {
    $sm.Add("  <url><loc>$siteUrl/$p</loc><changefreq>yearly</changefreq><priority>0.3</priority></url>")
}

$sm.Add('</urlset>')
[System.IO.File]::WriteAllText("$root\sitemap.xml", ($sm -join "`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Generated sitemap.xml ($($articles.Count) articles, $($tagList.Count) tags)"

# ===== rss.xml =====
$recent = $articles | Sort-Object { $_.publishedAt } -Descending | Select-Object -First 20
$rss = [System.Collections.Generic.List[string]]::new()
$rss.Add('<?xml version="1.0" encoding="UTF-8"?>')
$rss.Add('<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">')
$rss.Add('<channel>')
# NOTE: this file has no BOM, so PowerShell 5.1 reads it as ANSI. A literal em dash
# here would be written to the feed as mojibake -- use a numeric reference instead.
$rss.Add("  <title>$([System.Security.SecurityElement]::Escape($config.siteName)) &#8212; $([System.Security.SecurityElement]::Escape($config.tagline))</title>")
$rss.Add("  <link>$siteUrl</link>")
$rss.Add("  <description>$([System.Security.SecurityElement]::Escape($config.description))</description>")
$rss.Add("  <language>$($config.language)</language>")
$rss.Add("  <lastBuildDate>$((Get-Date).ToUniversalTime().ToString('ddd, dd MMM yyyy HH:mm:ss', $invariant)) +0000</lastBuildDate>")
$rss.Add("  <atom:link href=""$siteUrl/rss.xml"" rel=""self"" type=""application/rss+xml"" />")

foreach ($a in $recent) {
    $pubDate = [datetime]::ParseExact($a.publishedAt, 'yyyy-MM-dd', $invariant).ToString('ddd, dd MMM yyyy', $invariant) + ' 00:00:00 +0000'
    $excerpt = if ($a.excerpt) { [System.Security.SecurityElement]::Escape($a.excerpt) } else { '' }
    $rss.Add("  <item>")
    $rss.Add("    <title>$([System.Security.SecurityElement]::Escape($a.title))</title>")
    $rss.Add("    <link>$siteUrl/articles/$($a.id).html</link>")
    $rss.Add("    <description>$excerpt</description>")
    $rss.Add("    <pubDate>$pubDate</pubDate>")
    $rss.Add("    <guid isPermaLink=""true"">$siteUrl/articles/$($a.id).html</guid>")
    $rss.Add("  </item>")
}

$rss.Add('</channel>')
$rss.Add('</rss>')
[System.IO.File]::WriteAllText("$root\rss.xml", ($rss -join "`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Generated rss.xml ($($recent.Count) items)"

# ===== robots.txt =====
$robots = @"
User-agent: *
Allow: /

Sitemap: $siteUrl/sitemap.xml
"@
[System.IO.File]::WriteAllText("$root\robots.txt", $robots, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Generated robots.txt"

# ===== ads.txt =====
# AdSense will not serve on a domain without this file once the account has any
# ads.txt at all, and flags "earnings at risk" in the dashboard until it resolves.
# Written only when a client ID is configured; removed again if it is cleared, so
# a stale file cannot outlive the account it authorises.
$adsClientId = ''
if ($config.PSObject.Properties.Name -contains 'monetization' -and
    $config.monetization.adsense -and $config.monetization.adsense.clientId) {
    $adsClientId = $config.monetization.adsense.clientId
}
$adsTxtPath = "$root\ads.txt"
if ($adsClientId) {
    # ca-pub-0000000000000000 -> pub-0000000000000000, the publisher ID ads.txt wants.
    $pubId = $adsClientId -replace '^ca-', ''
    $adsTxt = "google.com, $pubId, DIRECT, f08c47fec0942fa0`n"
    [System.IO.File]::WriteAllText($adsTxtPath, $adsTxt, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "Generated ads.txt ($pubId)"
} elseif (Test-Path $adsTxtPath) {
    Remove-Item -LiteralPath $adsTxtPath
    Write-Host "Removed ads.txt (no AdSense client configured)"
}

# ===== articles-slim.json (for client-side search) =====
$slim = $articles | ForEach-Object {
    [PSCustomObject]@{
        id          = $_.id
        title       = $_.title
        excerpt     = if ($_.excerpt) { $_.excerpt } else { '' }
        category    = $_.category
        tags        = if ($_.tags) { $_.tags } else { @() }
        publishedAt = $_.publishedAt
    }
}
$slimJson = $slim | ConvertTo-Json -Depth 3 -Compress
[System.IO.File]::WriteAllText("$root\articles-slim.json", $slimJson, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Generated articles-slim.json ($($slim.Count) items)"
